import { createIconSet } from 'react-native-vector-icons';
const glyphMap = {
  inbound: '\uE90A',
  outbound: '\uE909',
  complete: '\uF139',
  setting: '\uF8BA',
  back: '\uF141',
  next: '\uF142',
  check: '\uF12C',
  more: '\uF1D8',
  scan: '\uF072',
  contact: '\uF004',
  filter: '\uF232',
  reset: '\uF99A',
  search: '\uF349',
  expand: '\uF140',
  collapse: '\uF143',
  box: '\uF131',
  boxChecked: '\uF132',
  boxIntermediate: '\uF375',
  keyboard: '\uF97A',
  circlePlay: '\uF40D',
  solidCirclePause: '\uF3E5',
  warehouseIcon: '\uF6D8',
  solidCircleCheck: '\uF5E0',
  plus: '\uF415',
  minus: '\uF374',
  trashCan: '\uFA79',
  selectPopup: '\uF35D',
  calendar: '\uFA31',
  add: '\uF419',
  print: '\uF42A',
  delete: '\uF159',
  list: '\uF279',
  location: '\uF7D8',
};
export const Icon = createIconSet(glyphMap, 'systumicon', 'systumicon.ttf');